[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"
  VITE_APP_BASE_URL = "https://liberacripto-prod.herokuapp.com"
  VITE_APP_GOOGLE_CLIENT_ID = "85606163053-hhk3hi1bl45hun7r51c1rq6au1vir7lq.apps.googleusercontent.com"


[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
